server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/gi-c/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service